### ISSUE TITLE
[Feature] Instead of specifying the env var 'INFRACOST_TERRAFORM_BINARY', infracost should use the default atlantis TF binary

### ISSUE THREAD

**Issue by richstokes** [infracost/infracost-atlantis#21]
This setting is already known by atlantis, infracost should scrape the `atlantis server --default-tf-version=` setting, and use this for its binary. 

Thanks!

**Comment by aliscott** [comment]
Good idea! It looks like this comes through as an`ATLANTIS_TERRAFORM_VERSION` env var (https://github.com/runatlantis/atlantis/blob/d914eafd2a3343fb22211018661bed1881b813e6/server/core/runtime/run_step_runner.go#L40) so Infracost could pick this up if it's present in the env.

**Comment by aliscott** [comment]
I don't think it will be needed since with those changes we recommend Infracost running against the SHOWFILE (Terraform plan JSON) so it doesn't run Terraform internally.

**Comment by alikhajeh1** [comment]
@richstokes we just released a big improvement (pretty much a rewrite) of the [Infracost-Atlantis integration](https://github.com/infracost/infracost-atlantis). This means that setting `INFRACOST_TERRAFORM_BINARY` is no longer needed so I'm going to close this issue - if you have 5mins, it would great if you can review the [migration guide](https://www.infracost.io/docs/guides/atlantis_migration) and let me know if it makes sense.
