### ISSUE TITLE
Can this be updated to the latest Atlantis release? 

### ISSUE THREAD

**Issue by richstokes** [infracost/infracost-atlantis#23]
'looks like its on `v0.17.5` when using the `infracost/infracost-atlantis:latest` image. The current atlantis release is `v0.18.1`

**Comment by aliscott** [comment]
@richstokes I've merged https://github.com/infracost/infracost-atlantis/pull/20, so `infracost-atlantis:latest` uses `v0.18.1` as well as `infracost-atlantis:latest-atlantis0.18.1`. We've been thinking about how we maintain the versions going forward. If you have any ideas we have start a GitHub discussion for improvements to this integration here: https://github.com/infracost/infracost/discussions/1179#discussioncomment-1745560.

**Comment by chenrui333** [comment]
> 'looks like its on `v0.17.5` when using the `infracost/infracost-atlantis:latest` image. The current atlantis release is `v0.18.1`

yeah, `latest` image is released to the ghcr instead of docker hub. Should be good with my update.
