### ISSUE TITLE
Add Bitbucket example

### ISSUE THREAD

**Issue by DrFaust92** [infracost/infracost-atlantis#56]
Currently there is no precise bitbucket example (unlike others like GH and Gitlab)

Ill try to work on this myself as im currently doing this integration

**Comment by alikhajeh1** [comment]
Thanks @DrFaust92 - much appreciated! I suppose that can be added to [this page](https://github.com/infracost/infracost-atlantis/blob/master/examples/combined-infracost-comment/README.md).

In case it's helpful for the Atlantis integration, we have a [bitbucket pipeline example](https://bitbucket.org/infracost/infracost-bitbucket-pipeline) but really `infracost comment bitbucket` is the only interesting part of it.
