### ISSUE TITLE
Support arm image

### ISSUE THREAD

**Issue by FRABUCHI** [infracost/infracost-atlantis#66]
Will arm image be supported?
Currently, only amd images seem to be supported.

**Comment by alikhajeh1** [comment]
@FRABUCHI thanks for creating this, we [made](https://github.com/infracost/infracost/releases) ARM binaries for the CLI a while ago and we'd love community help on making ARM images for Atlantis. Looks like Atlantis [released](https://github.com/runatlantis/atlantis/pull/1483) an ARM image, which this task would need as we do [`FROM` atlantis](https://github.com/infracost/infracost-atlantis/blob/master/Dockerfile#L3) in the Dockerfile.
