### ISSUE TITLE
Can we add some guides on integrating Infracost alongside existing policy_checks

### ISSUE THREAD

**Issue by david-heward-unmind** [infracost/infracost-atlantis#68]
Many of us will already be using policy_check to check the terraform plan output and run conftest against it.

There is a lack of documentation available on how to achieve both conftest on the terraform plan file and the infracost json output.

Though conftest makes available `--combine` this is less than optimal as it would mean re-writing all existing policies to accommodate the combined input sources.

Thoughts?

**Comment by alikhajeh1** [comment]
@davidh-unmind I'm sorry that I somehow missed this issue, tagging in @tim775 who worked on the [conftest example](https://github.com/infracost/infracost-atlantis/blob/master/examples/conftest/README.md) in case he has any ideas.

Also, we recently released a [Guardrails feature](https://www.infracost.io/docs/infracost_cloud/guardrails/) in Infracost Cloud, would be great if you can take a quick look at that to see if that does what you want, or if you wanted to define custom OPA policies to trigger those notifications/actions?

**Comment by alikhajeh1** [comment]
Closing this issue as the Infracost GH App https://www.infracost.io/docs/integrations/github_app/ works with policies defined in Infracost Cloud.
