### ISSUE TITLE
github app instead of github token

### ISSUE THREAD

**Issue by cloudn8ve** [infracost/infracost-atlantis#79]
is it possible to use the github app token instead of the the github token

**Comment by bheemvennapureddy** [comment]
I was also looking for an answer on this

**Comment by alikhajeh1** [comment]
That should be possible as long as your token has access to post PR comments.

However, I would recommend using https://www.infracost.io/docs/integrations/github_app/ as it's a much simpler integration, the Infracost GH App parses TF HCL code directly and can be run independently of Atlantis.
